config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :projects do
  resources :items
  resources :markup
end

app/models/items.rb
class Items < ActiveRecord::Base


  belongs_to :issue, class_name: 'Issue'#, :inverse_of => :products

  validates_presence_of :name, :price, :amount, :issue_id
  validates_numericality_of :price, greater_than_or_equal_to: 0
  validates_numericality_of :amount,  greater_than_or_equal_to: 0
  validates_numericality_of :issue_id, greater_than_or_equal_to: 0
  validates_uniqueness_of :name


  def project
    @project ||= issue.project
  end

  def self.of_project(project)
    self.joins(:issue).joins('INNER JOIN projects ON projects.id = issues.project_id').where('projects.id = ?', project.id)
  end

  def self.of_issue(issue)
    self.joins(:issue).where('issues.id = ?', issue.id)
  end
end

app/models/markup.rb
class Markup < ActiveRecord::Base
  unloadable
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  unloadable
  helper :sort
  include SortHelper
  before_filter :find_project
  before_filter :authorize, :only => :index
  before_filter :find_item, :except => [:index, :new, :create]
  #before_filter :find_issue, :only => [:new, :create]


  def index
   (render_403; return false) unless User.current.allowed_to?(:view_operations, @project)
    sort_init 'name', 'desc'
    sort_update %w(name price amount manufacturing_date created_at)
    @items = Items.of_project(@project)
    @items = @items.where("items.name like ?", "%#{params[:name]}%") if params[:name].present?
    @items = @items.order(sort_clause)
  end


  def new
    (render_403; return false) unless User.current.allowed_to?(:add_operations, @project)
    @item = Items.new
  end

  def edit
    (render_403; return false) unless User.current.allowed_to?(:edit_operations, @project)
    @item = Items. find(params[:id])
  end

  def create
    (render_403; return false) unless User.current.allowed_to?(:add_operations, @project)
    @item = Items.create(params[:item])
   if @item.save
      flash[:notice] = l(:notice_successful_save)
      redirect_to :action => 'show', :id => @item
    else
      render :action => 'new'
    end
  end

  def update
    (render_403; return false) unless User.current.allowed_to?(:edit_operations, @project)
    @item = Items.find(params[:id])
    @item.update_attributes(params[:item])
    if @item.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to :action => 'show', :id => @item
    else
      render :action => 'edit'
    end
  end


  def destroy
    (render_403; return false) unless User.current.allowed_to?(:delete_operations, @project)
    @item = Items.find(params[:id])
    if @item.destroy
      flash[:notice] = l(:notice_successful_delete)
    else
      flash[:error] = l(:notice_unsuccessful_save)
    end
    respond_to do |format|
      format.html { redirect_back_or_default :action => "index", :project_id => params[:project_id] }

    end

  end

  def show
    (render_403; return false) unless User.current.allowed_to?(:view_operations, @project)
  end


  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def find_issue
    @issue ||= if params[:issue_id].present?
                 Issue.find(params[:issue_id])
               else
                 find_item.issue
               end
  end

  def find_item
    @item ||= Items.find(params[:id])
  end

end

app/controllers/markup_controller.rb
class MarkupController < ApplicationController
  unloadable
  before_filter :find_project
  private
  def find_project
    @project ||= if params[:project_id].present?
                   Project.find(params[:project_id])
                 else
                   find_issue.project
                 end
  end
  def index
  end
end

app/helpers/items_helper.rb
module ItemsHelper

  def sort_by_name(selected = nil)
    operation_categories = OperationCategory.order("#{OperationCategory.table_name}.is_income DESC").order(:position)
    return "" unless operation_categories.any?
  end
end

app/helpers/markup_helper.rb
module MarkupHelper
end

app/views/items/_form.html.erb
<%= error_messages_for 'item' %>

<div class="box tabular">

<div class="splitcontentleft">
  <p class="name"><%= f.text_field :name, :label => l(:field_item_name), :size => 10, :required => true %></p>
  <p class="price"><%= f.text_field :price, :label => l(:field_item_price), :size => 10, :required => true %></p>
  <p class="amount"><%= f.text_field :amount, :label => l(:field_item_amount), :size => 10, :required => true %></p>
  <p class="issue_id_"><%= f.select :issue_id, (Issue.all.map {|c| [c.subject, c.id]}), :required => true  %></p>

</div>

<div class="splitcontentright">
  <p><%= f.text_field :manufacturing_date, :size => 12, :required => true, :value => Time.now, :label => l(:field_item_manufacturing_date) %><%= calendar_for('item_manufacturing_date') %>
  </p>
</div>

<div style="clear:both;"> </div>

</div>

app/views/items/_issue.html.erb
<% if User.current.allowed_to?(:view_operations, @project) %>
    <hr/>
    <div class="contextual">

    </div>
    <p><strong><%= l(:label_item) %></strong></p>


    <table class="list">
      <thead>
      <tr>
        <th>#</th>
        <th><%= l(:field_item_name) %></th>
        <th><%= l(:field_item_price) %></th>
        <th><%= l(:field_item_amount) %></th>
        <th><%= l(:field_item_manufacturing_date) %></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% for item in Items.of_issue(issue) do -%>
          <tr class="<%= cycle("odd", "even") %>">
            <td><%= item.id %></td>
            <td><%= link_to item.name, project_item_path(item)%></td>
            <td><%= item.price %></td>
            <td><%= item.amount %></td>
            <td><%= format_time(item.manufacturing_date) unless item.manufacturing_date.nil?  %></td>

            <td class="buttons">
            <%= link_to l(:button_edit), edit_project_item_path(:project_id => @project, :id => item.id), :class => 'icon icon-edit' if User.current.allowed_to?(:edit_operations, item.project)%>
            <%= link_to l(:button_delete),project_item_path(:project_id => @project, :id => item.id), :method => :delete, :class => 'icon icon-del' if User.current.allowed_to?(:edit_operations, item.project) %>
            </td>
          </tr>
      <% end -%>
      </tbody>
    </table>


<% end %>

app/views/items/_table.html.erb
<div class="autoscroll">
  <table class="list">
    <thead>
    <tr>
      <th>#</th>
      <%= sort_header_tag('name', :caption => l(:field_item_name)) %>
      <%= sort_header_tag('price', :caption => l(:field_item_price)) %>
      <%= sort_header_tag('amount', :caption => l(:field_item_amount)) %>
      <%= sort_header_tag('manufacturing_date', :caption => l(:field_item_manufacturing_date)) %>
      <th><%= l(:field_issue) %></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% for item in @items do -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= item.id %></td>
          <td><%= link_to item.name,  :controller => 'items', :action => 'show', :id => item, :project_id => @project%></td>
          <td><%= item.price %></td>
          <td><%= item.amount %></td>
          <td><%= format_time(item.manufacturing_date) unless item.manufacturing_date.nil? %></td>

          <td><%= link_to_issue(item.issue) %></td>

          <td class="buttons">
            <%= link_to l(:button_edit), {:controller => 'items', :action => 'edit', :id => item},:class => 'icon icon-edit' if User.current.allowed_to?(:edit_operations, @project) %>
            <%= link_to l(:button_delete), {:controller => 'items', :action => 'destroy', :id => item}, :class => 'icon icon-del', :method => :delete if User.current.allowed_to?(:delete_operations, @project) %>

          </td>
        </tr>
    <% end -%>
    </tbody>
  </table>
</div>

app/views/items/create.html.erb
<h2>ProductsController#create</h2>

app/views/items/edit.html.erb
<% if User.current.allowed_to?(:edit_operations, @project) %>
  <% html_title t(:label_item) %>
  <h2><%= t(:project_module_warehouse) %></h2>
  <%= labelled_form_for :item, @item, :url => {:controller => 'items', :action => 'update', :project_id => @project}, :method => :put do |f|  %>
    <%= render :partial => 'form', :locals => {:f => f}  %>
    <%= submit_tag l(:button_save) if User.current.allowed_to?(:edit_operations, @project) -%>
  <% end -%>
<% end -%>

app/views/items/index.html.erb
<% html_title t(:label_item) %>

<div class="contextual">
  <%= link_to l(:label_item_new), {:controller => 'items', :action => 'new',:project_id => @project}, :class => 'icon icon-add' if User.current.allowed_to?(:add_operations, @project) %>
</div>

<h2><%= t(:project_module_warehouse) %></h2>

  <%= form_tag({:controller=> 'items', :action =>'index'}, :method => :get) do %>

      <%= hidden_field_tag :project_id, @project.id %>

    <fieldset><legend><%= l(:label_filter_plural) %></legend>
      <label for='name'><%= l(:field_item_name) %>:</label>
      <%= text_field_tag 'name', params[:name], :size => 50 %>
      <%= submit_tag l(:button_apply), :class => "small", :name => nil %>
      <%= link_to l(:button_clear), {:controller=> 'items', :action =>'index', project_id: @project}, :class => 'icon icon-reload' %>
    </fieldset>
<% end %>
&nbsp;

<%= render :partial => 'items/table', :locals => {items: @Items, project: @project} %>

app/views/items/new.html.erb
<% if User.current.allowed_to?(:edit_operations, @project) %>
  <% html_title t(:label_item) %>

  <h2><%= t(:project_module_warehouse) %></h2>

  <%= labelled_form_for :item, @item, :url => {:action => 'create', :project_id => @project}, :method => :post do |f|  %>
    <%= render :partial => 'form', :locals => {:f => f}  %>
    <%= submit_tag l(:button_save) if User.current.allowed_to?(:add_operations, @project) -%>
  <% end -%>
<% end -%>

app/views/items/show.html.erb
<% if User.current.allowed_to?(:view_operations, @project) %>

<% html_title t(:label_item) %>



<div class="contextual">
  <%= link_to l(:button_edit), {:controller=> 'items', :action => 'edit', :id => params[:id]}, :class => 'icon icon-edit' if User.current.allowed_to?(:edit_operations, @item.project) %>
  <%= link_to l(:button_delete), {:controller => 'items', :action => 'destroy', :id => params[:id]}, :class => 'icon icon-del', :method => :delete if User.current.allowed_to?(:delete_operations, @item.project) %>
</div>

<h2><%= @item.name %></h2>

<div class="splitcontentleft">
  <fieldset class="box tabular">
         <p>
      <label><%= l(:field_item_name )%> :</label> <%= @item.name %>
    </p>
     <p>
      <label><%= l(:field_item_price)%> :</label> <%= @item.price%>
    </p>
    <p>
      <label><%= l(:field_item_amount )%> :</label> <%= @item.amount %>
    </p>
    <% if @item.manufacturing_date%>
        <p>
          <label><%= l(:field_item_manufacturing_date)%> :</label> <%= format_time(@item.manufacturing_date)%>
        </p>
    <% end %>
    <p>
      <label><%= l(:field_issue)%> :</label> <%= link_to_issue(@item.issue) %>
    </p>
    <p>
      <label><%= l(:field_project)%> :</label> <%= link_to_project(@item.project) %>
    </p>
  </fieldset>
</div>
<% else %>
<%= render_403 %>
<% end %>

app/views/markup/_table.html.erb
<div class="autoscroll">
<% (1..7).each do |i| %>
    <table class="issues index">
    <tbody>
        <tr class="hascontextmenu ">

            <td class="checkbox">
                <%= check_box_tag "active", 1, true %>
            </td>
            <td class="info">
                <div class="theme"> Перезвонить по важному вопросу</div>
                <div class="time"> Сегодня, 14:00</div>
                <div class="tags">
                 <%= submit_tag "Метка 1", :type => 'button', :onclick => 'alert("Метка 1 была выбрана")',:class => 'button white small' %>
                 <%= submit_tag "Метка 2", :type => 'button', :onclick => 'alert("Метка 2 была выбрана")',:class => 'button white small' %>
                </div>
            </td>

            <td class="issue_type">Тип задачи</td>
            <td class="avatar">
                <div class="avatar"> </div>
            </td>
            <td class="name">
                <div class = "name">Иванов Иван Иванович</div>
                <div class = "company" >ООО "Ромашка"</div>
            </td>


        </tr>

    </tbody>
    </table>
    <% end %>
 </div>

app/views/markup/index.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'markup', :plugin => 'redmine_warehouse' %>
<% end %>
<% html_title ("Верстка") %>


<div class="contextual">
    <%= link_to ('Новая задача'),{}, {:class => 'icon icon-email', :style=>'text-decoration: underline;'} %>
</div>
<div class="content"><h1>Задачи</h1>

<%= render :partial => 'markup/table' %>
</div>
<% content_for :sidebar do %>
    <h3>Heading 3</h3>
    <%= link_to ('This is a text link'),{},{:style=>'text-decoration: underline;'} %></br>
    <%= link_to ('This is a text link'),{},{:style=>'text-decoration: underline;'} %></br>
    <%= link_to ('This is a text link'),{},{:style=>'text-decoration: underline;'} %></br>

<% end %>